---
title: "Daniel IAO"
subtitle: "Academic & Consultant"
about:
  template: trestles
  image-width: 14em
  image-shape: round
  links:
    - text: "{{< ai orcid >}}"
      href: https://orcid.org/0000-0002-0394-3827
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/daniel-itzamna-avila-ortega/
    - icon: github
      text: GitHub
      href: https://github.com/danieliavila
    - icon: envelope
      text: Email
      href: "mailto:daniel.avila@su.se"
  #type: grid                 # Options: grid, default (list), or table
  #sort: "date desc"          # Sorts newest projects first
  #categories: true           # Adds clickable category tags (e.g., "Python", "R")
---

## Overview

Welcome to my research, consultancy and opinion portfolio. My work focuses on sustainability sciences at large with a special focus on industrial ecology, social-ecological systems and social ecology. While I mostly engage with quantitative analyses, I have also explored and applied qualitative methodologies spanning workshops, reviews, interviews, among others. At my core, I approach this with a complex systems lens.

This portal serves as an interactive hub for my on-going projects, including materials prepared for the **World Biodiversity Forum at Davos, Switzerland**.

My ongoing projects are mostly associated with my PhD at the [Stockholm Resilience Centre \| Stockholm University](https://www.stockholmresilience.org), including:

### Research

- [Accounting for biodiversity impacts of consumption and production: current gaps and frontiers.](research/art1-phd.qmd)
- [The Hidden Cost of Biodiversity and Land Use: How Ecological Models Shape our Biodiversity Metrics.](research/art2-phd.qmd)
- [Sustainable Agriculture and Planetary Boundaries: Exploring the Socioeconomic and Socio-ecological footprints of Mexico’s Agricultural Sector.](research/art5-phd.qmd)

### Teaching
- [Bachelor’s Programme in Business, Ethics and Sustainability](https://www.su.se/english/education/course-catalogue/sf/sfehk)
  - The biosphere and humankind
  - Corporations and sustainable development in the Anthropocene I
  - Corporations and sustainable development in the Anthropocene II


### Interests

- Complex Systems
- Corporate Sustainability
- Networks and Data
- Justice, Inequality, Equity

<!--
- [Planetary Bundles Embedded in trade.](research/art3-phd.qmd)




- 
-->

